[project]
name = "template_loader"
version = "0.1.0"
description = "This is a simple template loader"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
    "torch>=2.6.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
]
