[project]
name = "classification-kan"
version = "0.1.0"
description = "Code for a KAN-based classification neural network."
readme = "README.md"
requires-python = ">=3.11.13"
dependencies = [
    "pykan",
    "torch"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
]
